from .base import get_db_connection
from .migrations import init_db
from .repos.bgm_repo import get_all_bgm, insert_or_update_bgm
from .repos.media_repo import (
    get_all_movies,
    get_library_stats,
    get_movies_missing_posters,
    get_movies_with_meta,
    sync_movies_to_meta,
    update_movie_poster,
    upsert_movie_metadata,
)
from .repos.quote_repo import get_golden_quotes
from .repos.subtitle_repo import (
    check_file_exists,
    delete_records_by_path,
    fetch_subtitles_by_ids,
    get_all_file_paths,
    get_context_by_id,
    get_file_hash_path_index,
    get_file_paths_by_hash,
    get_subtitle_ids_by_paths,
    insert_subtitles_batch,
    insert_subtitles_with_metadata_batch,
    iter_subtitles_for_vector_rebuild,
    search_keyword,
    update_subtitle_embedding_metadata_batch,
)
from .repos.tag_repo import (
    add_tag,
    get_movie_tags,
    get_subtitle_tags,
    get_tags_by_type,
    link_tag_to_movie,
    link_tag_to_quote,
    link_tag_to_subtitle,
    search_subtitles_by_tags,
)

__all__ = [
    "add_tag",
    "check_file_exists",
    "delete_records_by_path",
    "fetch_subtitles_by_ids",
    "get_all_bgm",
    "get_all_file_paths",
    "get_all_movies",
    "get_context_by_id",
    "get_db_connection",
    "get_file_hash_path_index",
    "get_file_paths_by_hash",
    "get_golden_quotes",
    "get_library_stats",
    "get_movie_tags",
    "get_movies_missing_posters",
    "get_movies_with_meta",
    "get_subtitle_ids_by_paths",
    "get_subtitle_tags",
    "get_tags_by_type",
    "init_db",
    "insert_or_update_bgm",
    "insert_subtitles_batch",
    "insert_subtitles_with_metadata_batch",
    "iter_subtitles_for_vector_rebuild",
    "link_tag_to_movie",
    "link_tag_to_quote",
    "link_tag_to_subtitle",
    "search_keyword",
    "search_subtitles_by_tags",
    "sync_movies_to_meta",
    "update_movie_poster",
    "update_subtitle_embedding_metadata_batch",
    "upsert_movie_metadata",
]
